steps:
- name: 'gcr.io/k8s-skaffold/pack'
  entrypoint: 'pack'
  args: [
    'build', 
    '--builder=gcr.io/buildpacks/builder:v1', 
    '--path', './3-even-smarter-bot/score-monitor-service', 
    '--publish', 'us-docker.pkg.dev/$PROJECT_ID/bots-repo/score-monitor-service:$COMMIT_SHA'
  ]

- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'run',
    'deploy',
    '--image=us-docker.pkg.dev/$PROJECT_ID/bots-repo/score-monitor-service:$COMMIT_SHA',
    '--platform=managed',
    '--project=$PROJECT_ID',
    '--service-account=cloudrun-bot@microbot-hackathon.iam.gserviceaccount.com',
    '--region=us-central1',
    '--allow-unauthenticated',
    '--memory=256Mi',
    'score-monitor-service'
  ]
